workspace = { members = ["my_lib"] }
[package]
name = "create_a_library_with_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_lib = { path = "./my_lib" }
